version: '3.7'

services:
  jms:
    image: rmohr/activemq
    environment:
      - "TZ=Europe/Berlin"
    ports:
      - "61616:61616" # JMS broker (admin:adminactivemq) (amq:amq)
      - "8161:8161"   # Web admin UI http://localhost:8161 (admin:admin)
  game-of-three-app:
    container_name: game-of-three-app
    restart: on-failure
    image: game-of-three-service
    build: .
    ports:
      - "7070:7070"
    networks:
      game-of-three-network:

networks:
  game-of-three-network: