server:
  port: 7070
---
spring:
  profiles:
    active: local
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
---
stomp:
  endpoint:
    allowed-origin-patterns: "*"

---
game-of-three:
  first_player_index: 0

activemq:
  destination: playermove

